server:
  port: 8080

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 8640000 # a day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
